# Generated by Django 4.2.30 on 2026-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='tipo',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_p1',
            field=models.FloatField(null=True, verbose_name='P1'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_p2',
            field=models.FloatField(null=True, verbose_name='P2'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_t1',
            field=models.FloatField(null=True, verbose_name='T1'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_t2',
            field=models.FloatField(null=True, verbose_name='T2'),
        ),
    ]
