# Generated by Django 4.2.30 on 2026-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_remove_nota_nota_remove_nota_tipo_nota_nota_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano',
            field=models.PositiveIntegerField(null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='nota',
            name='periodo',
            field=models.CharField(choices=[('1_trimestre', '1° Trimestre'), ('2_trimestre', '2° Trimestre'), ('3_trimestre', '3° Trimestre')], default='1_trimestre', verbose_name='Período/Trimestre'),
        ),
    ]
