# Generated by Django 4.2.30 on 2026-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_nota_ano_nota_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota_p1',
            field=models.FloatField(blank=True, null=True, verbose_name='P1'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_p2',
            field=models.FloatField(blank=True, null=True, verbose_name='P2'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_t1',
            field=models.FloatField(blank=True, null=True, verbose_name='T1'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_t2',
            field=models.FloatField(blank=True, null=True, verbose_name='T2'),
        ),
    ]
