# Generated by Django 4.2.30 on 2026-06-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_nota_nota_p1_alter_nota_nota_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='situacao',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('recuperacao', 'Em recuperação'), ('reprovado', 'Reprovado'), ('cursando', 'Cursando')], verbose_name='Situação'),
        ),
    ]
