# Generated by Django 4.2.30 on 2026-06-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_nota_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='media_final',
            field=models.FloatField(blank=True, null=True, verbose_name='Média Final'),
        ),
    ]
