# Generated by Django 4.2.30 on 2026-06-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_nota_media_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='periodo',
        ),
    ]
