# Generated by Django 4.2.30 on 2026-08-23 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0007_remove_nota_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade_aula', 'Atividade em aula')], default='prova', verbose_name='Tipo')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='valor')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.disciplina', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.avaliacao', verbose_name='Avaliação')),
            ],
        ),
    ]
