# Generated by Django 4.2.30 on 2026-08-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_avaliacao_notaavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
