# Generated by Django 4.2.30 on 2026-09-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_avaliacao_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='criado_em',
        ),
    ]
