# Generated by Django 4.2.30 on 2026-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_remove_disciplina_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='modo_calculo',
            field=models.CharField(choices=[('soma', 'Soma dos pesos'), ('ponderada', 'Média ponderada'), ('aritmetica', 'Média aritmética')], default='ponderada', max_length=20, verbose_name='Modo de cálculo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
