# Generated by Django 4.2.30 on 2026-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_disciplina_ativo_disciplina_modo_calculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='situacao',
            field=models.CharField(max_length=20, choices=[('aprovado', 'Aprovado'), ('recuperacao', 'Em recuperação'), ('exame', 'Exame'), ('reprovado', 'Reprovado'), ('cursando', 'Cursando')], verbose_name='Situação'),
        ),
    ]
