# Generated by Django 4.2.30 on 2026-09-13 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0012_alter_nota_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota_p1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_p2',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_t1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_t2',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_exame',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota do Exame'),
        ),
        migrations.AlterUniqueTogether(
            name='notaavaliacao',
            unique_together={('aluno', 'avaliacao')},
        ),
    ]
