# Generated by Django 4.2.30 on 2026-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0013_remove_nota_nota_p1_remove_nota_nota_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='modo_calculo',
            field=models.CharField(choices=[('soma', 'Soma dos pesos'), ('ponderada', 'Média ponderada'), ('aritmetica', 'Média aritmética')], max_length=20, verbose_name='Modo de cálculo'),
        ),
    ]
