# Generated by Django 4.2.30 on 2026-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0014_alter_disciplina_modo_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='modo_calculo',
            field=models.CharField(blank=True, choices=[('soma', 'Soma dos pesos'), ('ponderada', 'Média ponderada'), ('aritmetica', 'Média aritmética')], max_length=20, null=True, verbose_name='Modo de cálculo'),
        ),
    ]
