# Generated by Django 4.2.30 on 2026-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_alter_disciplina_modo_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='ano',
        ),
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.PositiveIntegerField(null=True, verbose_name='Ano'),
        ),
    ]
