# Generated by Django 4.2.30 on 2026-09-20 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0017_preencher_ano_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.turma', verbose_name='Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'turma')},
        ),
    ]
