# Generated by Django 4.2.30 on 2026-09-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0022_nota_matricula_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.turma', verbose_name='Turma'),
        ),
    ]
